--------------------------------------------------------
--  DDL for Table REDDITCOMMENTS
--------------------------------------------------------
DROP TABLE dbuser.redditcomments;

  CREATE TABLE "DBUSER"."REDDITCOMMENTS" 
   (	"COMMENT_ID" VARCHAR2(20 BYTE), 
	"SUBREDDIT" VARCHAR2(20 BYTE), 
	"AUTHOR" VARCHAR2(20 BYTE), 
	"R_COMMENT" VARCHAR2(4000 BYTE), 
	"R_SCORE" NUMBER, 
	"R_DATE" VARCHAR2(4000 BYTE), 
	"PATTERN_POLARITY" NUMBER(18,5), 
	"NAIVESBAYES_POSITIVE" NUMBER(18,5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
